### ISSUE TITLE
Accessibility colors using "prefers-contrast" media query

### ISSUE THREAD

**Issue by au5ton** [EvanBacon/expo-apple-colors#5]
I noticed that on the Apple website there are differences in the system colors when a specific accessibility setting is changed. I'm not familiar with this. Would something like this be considered?

![image](https://github.com/user-attachments/assets/f06481f6-a381-4e72-b43e-9d97be4e30b9)

https://developer.apple.com/design/human-interface-guidelines/color#Specifications

**Comment by EvanBacon** [comment]
something like what? all the colors are native on apple platforms, there are best-effort fallbacks on other platforms.

**Comment by EvanBacon** [comment]
Perhaps this CSS media query could be used as a fallback on web, but bundle size is important on web so maybe not worth the extra code https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-contrast
